// Cloud Firestore Seed Initializer with realistic collegiate data for SICM
import {
  StudentDocument,
  TeacherDocument,
  SubjectDocument,
  TimetableSlot,
  AssignmentDocument,
  MaterialDocument,
  AnnouncementDocument,
} from './firestore';

export const SEED_STUDENTS: StudentDocument[] = [
  {
    id: 's-1',
    userId: 'u-student-1',
    name: 'Aarav Sharma',
    rollNumber: '22BCA001',
    registerNumber: 'U18CM21S0001',
    programCode: 'BCA',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
    email: 'aarav.sharma@sicm.edu.in',
    contactNumber: '+91 99000 48291',
  },
  {
    id: 's-2',
    userId: 'u-student-2',
    name: 'Diya Patel',
    rollNumber: '22BCA002',
    registerNumber: 'U18CM21S0002',
    programCode: 'BCA',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
    email: 'diya.patel@sicm.edu.in',
    contactNumber: '+91 98450 12345',
  },
  {
    id: 's-3',
    userId: 'u-student-3',
    name: 'Rohan Verma',
    rollNumber: '22BCA003',
    registerNumber: 'U18CM21S0003',
    programCode: 'BCA',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
    email: 'rohan.verma@sicm.edu.in',
    contactNumber: '+91 97410 98765',
  },
];

export const SEED_TEACHERS: TeacherDocument[] = [
  {
    id: 't-1',
    userId: 'u-teacher-1',
    name: 'Dr. Pratibha Rao',
    employeeCode: 'EMP101',
    email: 'dr.pratibha.rao@sicm.edu.in',
    departmentName: 'Computer Applications',
    designation: 'Associate Professor',
    isAvailable: true,
  },
  {
    id: 't-2',
    userId: 'u-teacher-2',
    name: 'Prof. K. R. Sharma',
    employeeCode: 'EMP102',
    email: 'kr.sharma@sicm.edu.in',
    departmentName: 'Computer Applications',
    designation: 'Assistant Professor',
    isAvailable: true,
  },
  {
    id: 't-3',
    userId: 'u-teacher-3',
    name: 'Dr. Suresh Kumar',
    employeeCode: 'EMP103',
    email: 'suresh.kumar@sicm.edu.in',
    departmentName: 'Computer Applications',
    designation: 'Professor & Head',
    isAvailable: true,
  },
  {
    id: 't-4',
    userId: 'u-teacher-4',
    name: 'Prof. Ananya Sen',
    employeeCode: 'EMP104',
    email: 'ananya.sen@sicm.edu.in',
    departmentName: 'Computer Applications',
    designation: 'Assistant Professor',
    isAvailable: true,
  },
  {
    id: 't-5',
    userId: 'u-teacher-5',
    name: 'Prof. Ramesh Bhat',
    employeeCode: 'EMP105',
    email: 'ramesh.bhat@sicm.edu.in',
    departmentName: 'Computer Applications',
    designation: 'Lecturer',
    isAvailable: true,
  },
];

export const SEED_SUBJECTS: SubjectDocument[] = [
  {
    id: 'sub-bca401',
    code: 'BCA401',
    name: 'Python Programming',
    credits: 4,
    semesterNumber: 4,
    departmentName: 'Computer Applications',
    teacherId: 't-2',
    teacherName: 'Prof. K. R. Sharma',
  },
  {
    id: 'sub-bca402',
    code: 'BCA402',
    name: 'Software Engineering',
    credits: 4,
    semesterNumber: 4,
    departmentName: 'Computer Applications',
    teacherId: 't-3',
    teacherName: 'Dr. Suresh Kumar',
  },
  {
    id: 'sub-bca404',
    code: 'BCA404',
    name: 'Operating Systems',
    credits: 4,
    semesterNumber: 4,
    departmentName: 'Computer Applications',
    teacherId: 't-1',
    teacherName: 'Dr. Pratibha Rao',
  },
  {
    id: 'sub-bca403',
    code: 'BCA403',
    name: 'Database Management Systems',
    credits: 4,
    semesterNumber: 4,
    departmentName: 'Computer Applications',
    teacherId: 't-4',
    teacherName: 'Prof. Ananya Sen',
  },
  {
    id: 'sub-bca405',
    code: 'BCA405',
    name: 'Computer Networks',
    credits: 4,
    semesterNumber: 4,
    departmentName: 'Computer Applications',
    teacherId: 't-5',
    teacherName: 'Prof. Ramesh Bhat',
  },
  {
    id: 'sub-bca406',
    code: 'BCA406',
    name: 'DBMS Laboratory Session',
    credits: 2,
    semesterNumber: 4,
    departmentName: 'Computer Applications',
    teacherId: 't-4',
    teacherName: 'Prof. Ananya Sen',
  },
];

export const SEED_TIMETABLE: TimetableSlot[] = [
  {
    id: 'slot-mon-1',
    dayOfWeek: 'Monday',
    periodNumber: 1,
    startTime: '08:30',
    endTime: '09:30',
    subjectId: 'sub-bca401',
    subjectCode: 'BCA401',
    subjectName: 'Python Programming',
    teacherId: 't-2',
    teacherName: 'Prof. K. R. Sharma',
    roomNumber: 'Lab 2',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
  },
  {
    id: 'slot-mon-2',
    dayOfWeek: 'Monday',
    periodNumber: 2,
    startTime: '09:30',
    endTime: '10:30',
    subjectId: 'sub-bca402',
    subjectCode: 'BCA402',
    subjectName: 'Software Engineering',
    teacherId: 't-3',
    teacherName: 'Dr. Suresh Kumar',
    roomNumber: 'Room 302',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
  },
  {
    id: 'slot-mon-3',
    dayOfWeek: 'Monday',
    periodNumber: 3,
    startTime: '10:45',
    endTime: '11:45',
    subjectId: 'sub-bca404',
    subjectCode: 'BCA404',
    subjectName: 'Operating Systems',
    teacherId: 't-1',
    teacherName: 'Dr. Pratibha Rao',
    roomNumber: 'Hall 302',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
  },
  {
    id: 'slot-mon-4',
    dayOfWeek: 'Monday',
    periodNumber: 4,
    startTime: '11:45',
    endTime: '12:45',
    subjectId: 'sub-bca403',
    subjectCode: 'BCA403',
    subjectName: 'Database Management Systems',
    teacherId: 't-4',
    teacherName: 'Prof. Ananya Sen',
    roomNumber: 'Room 304',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
  },
  {
    id: 'slot-mon-5',
    dayOfWeek: 'Monday',
    periodNumber: 5,
    startTime: '01:15',
    endTime: '02:15',
    subjectId: 'sub-bca405',
    subjectCode: 'BCA405',
    subjectName: 'Computer Networks',
    teacherId: 't-5',
    teacherName: 'Prof. Ramesh Bhat',
    roomNumber: 'Room 302',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
  },
  {
    id: 'slot-mon-6',
    dayOfWeek: 'Monday',
    periodNumber: 6,
    startTime: '02:15',
    endTime: '03:15',
    subjectId: 'sub-bca406',
    subjectCode: 'BCA406',
    subjectName: 'DBMS Laboratory Session',
    teacherId: 't-4',
    teacherName: 'Prof. Ananya Sen',
    roomNumber: 'Lab 1',
    sectionName: 'BCA 2nd Year',
    semesterNumber: 4,
  },
];

export const SEED_ASSIGNMENTS: AssignmentDocument[] = [
  {
    id: 'asg-1',
    subjectId: 'sub-bca404',
    subjectName: 'Operating Systems (BCA404)',
    title: 'Process Synchronization & Banker’s Algorithm',
    description: 'Implement deadlock avoidance using Banker’s algorithm in C/Python with test matrix inputs.',
    dueDate: '2026-08-28',
    maxMarks: 20,
    sectionName: 'BCA 2nd Year',
    teacherId: 't-1',
    createdAt: '2026-08-20',
    submissionsCount: 42,
  },
  {
    id: 'asg-2',
    subjectId: 'sub-bca403',
    subjectName: 'Database Management Systems (BCA403)',
    title: 'Relational Algebra & Complex SQL Queries',
    description: 'Write SQL queries with nested joins, window functions, and indexing benchmarks.',
    dueDate: '2026-08-30',
    maxMarks: 25,
    sectionName: 'BCA 2nd Year',
    teacherId: 't-4',
    createdAt: '2026-08-19',
    submissionsCount: 38,
  },
  {
    id: 'asg-3',
    subjectId: 'sub-bca401',
    subjectName: 'Python Programming (BCA401)',
    title: 'Object-Oriented Data Structures Project',
    description: 'Build a custom binary search tree class with traversal iterators and unit test assertions.',
    dueDate: '2026-09-02',
    maxMarks: 30,
    sectionName: 'BCA 2nd Year',
    teacherId: 't-2',
    createdAt: '2026-08-18',
    submissionsCount: 29,
  },
];

export const SEED_MATERIALS: MaterialDocument[] = [
  {
    id: 'mat-1',
    subjectId: 'sub-bca404',
    subjectName: 'Operating Systems (BCA404)',
    title: 'Unit 3: Memory Management & Virtual Paging Slides',
    type: 'SLIDES',
    fileUrl: '#',
    uploadedBy: 'Dr. Pratibha Rao',
    uploadedAt: '2026-08-19',
    fileSize: '4.2 MB',
  },
  {
    id: 'mat-2',
    subjectId: 'sub-bca403',
    subjectName: 'Database Management Systems (BCA403)',
    title: 'Complete Lab Manual with Schema DDL & Sample Queries',
    type: 'LAB_MANUAL',
    fileUrl: '#',
    uploadedBy: 'Prof. Ananya Sen',
    uploadedAt: '2026-08-15',
    fileSize: '2.8 MB',
  },
  {
    id: 'mat-3',
    subjectId: 'sub-bca401',
    subjectName: 'Python Programming (BCA401)',
    title: 'Standard Library Quick Reference & NumPy Cheatsheet',
    type: 'NOTES',
    fileUrl: '#',
    uploadedBy: 'Prof. K. R. Sharma',
    uploadedAt: '2026-08-12',
    fileSize: '1.5 MB',
  },
];

export const SEED_ANNOUNCEMENTS: AnnouncementDocument[] = [
  {
    id: 'ann-1',
    title: 'Internal Assessment - 1 Schedule Announced',
    content: 'The first internal assessment tests for all 4th Semester BCA courses will commence from September 10, 2026. Timetable published under notice board.',
    author: 'Office of the Principal',
    authorRole: 'ADMIN',
    targetRole: 'ALL',
    createdAt: '2026-08-20',
    priority: 'HIGH',
  },
  {
    id: 'ann-2',
    title: 'Campus Placement Orientation Workshop',
    content: 'Pre-placement training sessions for BCA undergraduate cohorts begin this Saturday in the Golden Jubilee Auditorium.',
    author: 'Placement & Career Guidance Cell',
    authorRole: 'ADMIN',
    targetRole: 'STUDENT',
    createdAt: '2026-08-18',
    priority: 'NORMAL',
  },
];
