'use client';

import React, { useEffect, useState } from 'react';
import AppShell from '@/components/layout/AppShell';
import { useAuth } from '@/context/AuthContext';
import { getAssetPath } from '@/lib/utils';
import Link from 'next/link';
import {
  Clock,
  MapPin,
  Users,
  QrCode,
  ClipboardCheck,
  Coffee,
  Calendar,
  CheckCircle2,
  ShieldCheck,
  Award,
} from 'lucide-react';
import {
  getTeacherDailySchedule,
  subscribeToDailyTimetable,
  DailyTimetablePeriod,
  AdminDailyGeneration,
} from '@/lib/dailyTimetableStore';

export default function TeacherDailySchedulePage() {
  const { user } = useAuth();
  const [selectedDate, setSelectedDate] = useState<string>(() => new Date().toISOString().split('T')[0]);
  const [dailyClasses, setDailyClasses] = useState<DailyTimetablePeriod[]>([]);
  const [generationMeta, setGenerationMeta] = useState<AdminDailyGeneration | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    const unsubscribe = subscribeToDailyTimetable(selectedDate, (gen) => {
      setGenerationMeta(gen);
      const teacherName = (user?.name || 'Dr. Pratibha Rao').toLowerCase();
      const teacherId = user?.teacherProfileId || 't-1';
      const slots = gen?.currentTimetables || [];
      const filtered = slots.filter((slot) => {
        const primaryName = (slot.teacher?.user?.name || (slot.teacher as any)?.name || '').toLowerCase();
        const subName = (slot.substituteTeacher?.user?.name || (slot.substituteTeacher as any)?.name || '').toLowerCase();
        const isPrimary = (primaryName.length > 0 && primaryName.includes(teacherName)) || slot.teacher?.id === teacherId;
        const isSub = (subName.length > 0 && subName.includes(teacherName)) || slot.substituteTeacherId === teacherId;
        return isPrimary || isSub;
      });
      const sorted = [...(filtered.length > 0 ? filtered : slots.slice(0, 5))].sort((a, b) => (a.slotNumber || 0) - (b.slotNumber || 0));
      setDailyClasses(sorted);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [user?.teacherProfileId, user?.name, selectedDate]);

  const handleSetToday = () => {
    const todayStr = new Date().toISOString().split('T')[0];
    setSelectedDate(todayStr);
  };

  const isToday = selectedDate === new Date().toISOString().split('T')[0];

  return (
    <AppShell>
      <div className="space-y-5 max-w-7xl mx-auto py-2">
        {/* Top Control Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-stone-200/80">
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h1 className="text-xl font-bold text-stone-900 tracking-tight">
                Daily Lecture Schedule
              </h1>
              <span className="inline-flex items-center gap-1 rounded bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700 border border-emerald-200 uppercase tracking-wider">
                <CheckCircle2 className="size-3 text-emerald-600" />
                Admin Generated & Active
              </span>
            </div>
            <p className="text-xs text-stone-500 font-medium mt-0.5">
              Official day timetable generated by Central Administration & Dean Office for <strong>{selectedDate}</strong> ({generationMeta?.dayOfWeek})
            </p>
          </div>

          {/* Date Selector & Today Quick Action */}
          <div className="flex items-center gap-2 shrink-0">
            <button
              type="button"
              onClick={handleSetToday}
              className={`px-3.5 py-1.5 text-xs font-semibold rounded-lg border transition-all cursor-pointer ${
                isToday
                  ? 'bg-blue-600 border-blue-600 text-white shadow-xs'
                  : 'bg-white border-stone-200 text-stone-700 hover:bg-stone-50 hover:text-stone-900'
              }`}
            >
              Today
            </button>

            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="rounded-lg border border-stone-200 bg-white px-3 py-1.5 text-xs font-semibold text-stone-800 shadow-2xs focus:border-blue-500 outline-none font-mono cursor-pointer"
            />
          </div>
        </div>

        {/* Master Institutional Timetable Document Card for Today */}
        <div className="rounded-2xl border border-stone-200 bg-white shadow-xs overflow-hidden">
          {/* Institutional Header Banner */}
          <div className="border-b border-stone-200 bg-gradient-to-r from-stone-50 via-blue-50/30 to-white text-stone-900 p-5 sm:p-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center gap-3.5">
                <div className="flex size-13 shrink-0 items-center justify-center rounded-xl bg-white p-1 shadow-2xs ring-1 border border-stone-200">
                  <img
                    src={getAssetPath('/logo.png')}
                    alt="SICM Emblem"
                    onError={(e) => {
                      const target = e.currentTarget;
                      if (!target.src.includes('/sicm-lms/')) {
                        target.src = '/sicm-lms/logo.png';
                      }
                    }}
                    className="h-full w-full object-contain"
                  />
                </div>
                <div className="space-y-0.5">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-blue-700 block">
                    Seshadripuram Educational Trust
                  </span>
                  <h2 className="text-base sm:text-lg font-bold tracking-tight text-stone-900">
                    SESHADRIPURAM INSTITUTE OF COMMERCE & MANAGEMENT
                  </h2>
                  <p className="text-xs text-stone-500 font-medium">
                    Central Timetable Governance • Academic Year 2026-2027
                  </p>
                </div>
              </div>

              {/* Faculty & Generation Status Meta Box */}
              <div className="bg-white rounded-xl px-4 py-2.5 border border-stone-200 shadow-2xs text-left sm:text-right shrink-0 space-y-0.5">
                <p className="text-xs font-bold text-stone-900">
                  PROFESSOR: {user?.name || 'Dr. Pratibha Rao'}
                </p>
                <p className="text-xs text-blue-700 font-mono font-semibold">
                  {generationMeta?.dayOfWeek} • {selectedDate}
                </p>
                <div className="flex items-center sm:justify-end gap-1 mt-1">
                  <span className="text-[9px] font-bold uppercase tracking-wider bg-blue-50 text-blue-800 px-2 py-0.5 rounded border border-blue-200">
                    {dailyClasses.length} Allocated Periods Today
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Generously Spaced Daily Timetable Table */}
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-stone-200 bg-stone-50 text-[10px] font-bold uppercase tracking-wider text-stone-600">
                  <th className="py-3 px-5 text-center w-20 border-r border-stone-200">Period</th>
                  <th className="py-3 px-5 w-44 border-r border-stone-200">Time Slot</th>
                  <th className="py-3 px-5 border-r border-stone-200">Course & Subject</th>
                  <th className="py-3 px-5 w-44 border-r border-stone-200">Class Cohort</th>
                  <th className="py-3 px-5 w-40 border-r border-stone-200">Lecture Hall / Lab</th>
                  <th className="py-3 px-5 text-right w-56">Attendance Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100 text-xs">
                {dailyClasses.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="py-14 text-center text-stone-400">
                      <Coffee className="size-8 text-stone-300 mx-auto mb-2" />
                      <p className="font-bold text-stone-700">No Lectures Scheduled for {generationMeta?.dayOfWeek}</p>
                      <p className="text-xs text-stone-400 mt-0.5">Admin has not scheduled teaching periods for this date.</p>
                    </td>
                  </tr>
                ) : (
                  dailyClasses.map((c) => {
                    const isSubstitute = c.isSubstitute || c.substituteTeacherId === (user?.teacherProfileId || 't-1');
                    const isLab = c.subject?.name?.toLowerCase().includes('lab');

                    return (
                      <React.Fragment key={c.id}>
                        {/* Period Row */}
                        <tr className="hover:bg-stone-50/70 transition-colors">
                          {/* Period # */}
                          <td className="py-4 px-5 text-center font-bold text-stone-900 border-r border-stone-100 bg-stone-50/30">
                            <span className="inline-flex size-7 items-center justify-center rounded-lg bg-blue-50 text-blue-900 font-bold text-xs border border-blue-200">
                              {c.slotNumber}
                            </span>
                          </td>

                          {/* Time Interval */}
                          <td className="py-4 px-5 border-r border-stone-100 font-mono text-stone-800 font-bold">
                            <div className="flex items-center gap-1 text-xs text-stone-900">
                              <Clock className="size-3.5 text-blue-600 shrink-0" />
                              <span>{c.timeSlot?.startTime} – {c.timeSlot?.endTime}</span>
                            </div>
                            <span className="text-[10px] text-stone-400 font-normal mt-0.5 block">60 Mins Duration</span>
                          </td>

                          {/* Course & Subject */}
                          <td className="py-4 px-5 border-r border-stone-100">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="font-mono text-[11px] font-bold text-blue-900 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded">
                                {c.subject?.code}
                              </span>
                              <span className="font-bold text-stone-900">
                                {c.subject?.name}
                              </span>
                              {isLab && (
                                <span className="rounded bg-cyan-50 border border-cyan-200 text-cyan-800 text-[9px] font-bold px-1.5 py-0.2">
                                  LAB PRACTICAL
                                </span>
                              )}
                              {isSubstitute && (
                                <span className="rounded bg-amber-50 border border-amber-300 text-amber-950 text-[9px] font-extrabold px-1.5 py-0.2">
                                  SUBSTITUTE
                                </span>
                              )}
                            </div>
                          </td>

                          {/* Class Cohort */}
                          <td className="py-4 px-5 border-r border-stone-100 font-medium text-stone-700">
                            <div className="font-bold text-stone-900">{c.section?.name}</div>
                            <div className="text-[11px] text-stone-400">{c.section?.totalStudents || 70} Scholars Enrolled</div>
                          </td>

                          {/* Venue / Room */}
                          <td className="py-4 px-5 border-r border-stone-100 font-medium text-stone-700">
                            <div className="flex items-center gap-1.5">
                              <MapPin className="size-3.5 text-stone-400 shrink-0" />
                              <span className="font-mono font-bold text-stone-900">{c.room?.roomNumber}</span>
                            </div>
                            <div className="text-[10px] text-stone-400 truncate max-w-36 mt-0.5">{c.room?.name}</div>
                          </td>

                          {/* Actions */}
                          <td className="py-4 px-5 text-right">
                            <div className="flex items-center justify-end gap-1.5 flex-wrap">
                              <Link
                                href={`/teacher/marks?sectionId=${c.section?.id || 'sec-2'}&subjectCode=${c.subject?.code || 'BCA401'}`}
                                className="px-2.5 py-1.5 rounded-lg border border-purple-200 bg-purple-50 hover:bg-purple-100 text-purple-900 font-semibold text-xs transition-all shadow-2xs inline-flex items-center gap-1"
                                title="Enter Internal Assessment & Marks"
                              >
                                <Award className="size-3 text-purple-700" />
                                <span>Marks</span>
                              </Link>
                              <Link
                                href={`/teacher/attendance?timetableId=${c.id}&date=${selectedDate}`}
                                className="px-2.5 py-1.5 rounded-lg border border-stone-200 bg-white hover:bg-stone-50 text-stone-800 font-semibold text-xs transition-all shadow-2xs"
                              >
                                Register
                              </Link>
                              <Link
                                href={`/teacher/qr-session?timetableId=${c.id}&date=${selectedDate}`}
                                className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs shadow-xs transition-all flex items-center gap-1"
                              >
                                <QrCode className="size-3" />
                                <span>Smart QR</span>
                              </Link>
                            </div>
                          </td>
                        </tr>

                        {/* Tea Break in clean theme after Period 2 */}
                        {c.slotNumber === 2 && (
                          <tr className="bg-amber-50/50 border-y border-amber-200/80">
                            <td colSpan={6} className="py-2.5 px-5 text-center">
                              <div className="flex items-center justify-center gap-2 text-amber-900 font-bold text-[11px]">
                                <Coffee className="size-3.5 text-amber-600" />
                                <span>COLLEGIATE TEA & MENTORSHIP RECESS (11:00 AM – 11:15 AM)</span>
                              </div>
                            </td>
                          </tr>
                        )}

                        {/* Lunch Break in clean theme after Period 4 */}
                        {c.slotNumber === 4 && (
                          <tr className="bg-orange-50/50 border-y border-orange-200/80">
                            <td colSpan={6} className="py-2.5 px-5 text-center">
                              <div className="flex items-center justify-center gap-2 text-orange-950 font-bold text-[11px]">
                                <Coffee className="size-3.5 text-orange-600" />
                                <span>INSTITUTIONAL LUNCH RECESS (01:15 PM – 01:45 PM)</span>
                              </div>
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
